# 3.1 无量纲化处理

In [5]:
# 【sklearn归一化】
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

import pandas as pd
pd.DataFrame(data)
#实现归一化
scaler = MinMaxScaler() #实例化
print("1",scaler)
scaler = scaler.fit(data) #fit，在这里本质是生成min(x)和max(x)
print("2",scaler)
result = scaler.transform(data) #通过接口导出结果
print("3",result)
result_ = scaler.fit_transform(data) #训练和导出结果一步达成
print("4",result_)
scaler.inverse_transform(result) #将归一化后的结果逆转
#使用MinMaxScaler的参数feature_range实现将数据归一化到[0,1]以外的范围中

"""data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler(feature_range=[5,10]) #依然实例化
result = scaler.fit_transform(data) #fit_transform一步导出结果
print(result)"""
#当X中的特征数量非常多的时候，fit会报错并表示，数据量太大了我计算不了
#此时使用partial_fit作为训练接口
#scaler = scaler.partial_fit(data)

1 MinMaxScaler()
2 MinMaxScaler()
3 [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
4 [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


'data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]\nscaler = MinMaxScaler(feature_range=[5,10]) #依然实例化\nresult = scaler.fit_transform(data) #fit_transform一步导出结果\nprint(result)'

In [6]:
#【numpy归一化】
import numpy as np
X = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])
#归一化
X_nor = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [10]:
#【 sklearn 标准化】
from sklearn.preprocessing import StandardScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = StandardScaler() #1 实例化
scaler.fit(data) #2 fit，本质是生成均值和方差
# scaler.mean_ #查看均值的属性mean_
# scaler.var_ #查看方差的属性var_
x_std = scaler.transform(data) #3 通过接口导出结果
print(x_std)
# x_std.mean() #导出的结果是一个数组，用mean()查看均值
# x_std.std() #用std()查看方差
scaler.fit_transform(data) #使用fit_transform(data)一步达成结果
scaler.inverse_transform(x_std) #使用inverse_transform逆转标准化

[[-1.18321596 -1.18321596]
 [-0.50709255 -0.50709255]
 [ 0.16903085  0.16903085]
 [ 1.52127766  1.52127766]]


array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

# 3.2 缺失值处理